# Generated by Django 2.2.7 on 2019-12-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RUNNING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=160)),
                ('algorithm', models.CharField(max_length=320)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
