# Generated by Django 2.2.7 on 2019-12-23 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
