# Generated by Django 2.2.7 on 2019-12-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_remove_running_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='running',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
